Data Science Jobs on Glassdoor Dataset cleaning

In [68]:
import pandas as pd
import numpy as np
import re

In [69]:
df=pd.read_csv(r"C:\Users\rabbi\OneDrive\Documents\DATA ANALYSIS\Data Analystics\PYTHON\Data cleaning\Data Science Jobs on Glassdoor\Report\Data Science jobs on glassdoor.csv")

In [70]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
668,668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
669,669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1
670,670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1
671,671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1

In [71]:
df=df.drop_duplicates()
df["Salary Estimate"] = df["Salary Estimate"].str.strip("(Glassdoor est.)").str.replace("K", "").str.replace("$", "")
df2 = df.rename(columns={"Salary Estimate": "Salary Estimate (000)"})
df["Job Description"] = df["Job Description"].str.replace("\n", ":")
def replace_multiple_colon(text):
    return re.sub(r'(:)+', ':', text)

df["Job Description"] = df["Job Description"].apply(replace_multiple_colon)
df["Company Name"] = df["Company Name"].apply(lambda x: re.sub(r'[\d\n\.\--]', '', x))
df[['City', 'State']] = df['Location'].str.split(',', n=1, expand=True)
df = df.reset_index(drop=True)
df = df.drop(columns="Location")

In [72]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,City,State
0,0,Sr Data Scientist,137-171,Description:The Senior Data Scientist is respo...,3.1,Healthfirst,"New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",New York,NY
1,1,Data Scientist,137-171,"Secure our Nation, Ignite your Future:Join the...",4.2,ManTech,"Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,Chantilly,VA
2,2,Data Scientist,137-171,Overview:Analysis Group is one of the largest ...,3.8,Analysis Group,"Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,Boston,MA
3,3,Data Scientist,137-171,JOB DESCRIPTION:Do you have a passion for Data...,3.5,INFICON,"Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",Newton,MA
4,4,Data Scientist,137-171,Data Scientist:Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",New York,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,Data Scientist,105-167,Summary:We’re looking for a data scientist to ...,3.6,TRANZACT,"Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,Fort Lee,NJ
668,668,Data Scientist,105-167,Job Description:Become a thought leader within...,-1.0,JKGT,-1,-1,-1,-1,-1,-1,-1,-1,San Francisco,CA
669,669,Data Scientist,105-167,Join a thriving company that is changing the w...,-1.0,AccessHope,-1,-1,-1,-1,-1,-1,-1,-1,Irwindale,CA
670,670,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1,San Francisco,CA
671,671,Data Scientist,105-167,Description:The Data Scientist will be part of...,2.7,Flowers,"Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1,New York,NY

In [73]:
df.to_csv(r"C:\Users\rabbi\OneDrive\Documents\DATA ANALYSIS\Data Analystics\PYTHON\Data cleaning\Data Science Jobs on Glassdoor\Report\Clean_DS_Dataset.csv", index=False)